# Generated by Django 2.2.7 on 2019-11-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_subjects'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[(0, 'Not Marked'), (1, 'Present'), (2, 'Absent'), (3, 'Cancelled')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
                ('timetable_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.TimetablePeriod')),
            ],
        ),
    ]
