# Generated by Django 2.2.7 on 2019-11-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20191115_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableperiod',
            name='section',
        ),
    ]
