# Generated by Django 2.2.7 on 2019-11-15 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_subjects'),
        ('attendance', '0005_remove_timetableperiod_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableperiod',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Section'),
            preserve_default=False,
        ),
    ]
