# Generated by Django 2.2.7 on 2019-11-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_subjects'),
        ('attendance', '0006_timetableperiod_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableperiod',
            unique_together={('day', 'time', 'section')},
        ),
    ]
