# Generated by Django 2.2.7 on 2019-11-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20191115_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='value',
            field=models.CharField(choices=[(-1, 'Not Marked'), (1, 'Present'), (0, 'Absent'), (2, 'Cancelled')], max_length=1),
        ),
        migrations.AlterField(
            model_name='timetableperiod',
            name='day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1),
        ),
    ]
